- epg: epg-000086_001
  site_code: EID
  subnet: 10.235.23.0.1/24
  vlan_id: 268
  vrf_name: vrf-eid_app_centric
- epg: epg-000087_001
  site_code: EID
  subnet: 10.235.24.0.1/24
  vlan_id: 270
  vrf_name: vrf-eid_app_centric
- epg: epg-000086_001
  site_code: EID
  subnet: 10.235.23.0.1/24
  vlan_id: 268
  vrf_name: vrf-eid_app_centric
- epg: epg-000087_001
  site_code: EID
  subnet: 10.235.24.0.1/24
  vlan_id: 270
  vrf_name: vrf-eid_app_centric
- epg: epg-000088_001
  site_code: HTC
  subnet: 10.236.21.0.1/24
  vlan_id: 367
  vrf_name: vrf-htc_app_centric
- epg: epg-000089_001
  site_code: HTC
  subnet: 10.236.22.0.1/24
  vlan_id: 368
  vrf_name: vrf-htc_app_centric
- epg: epg-000088_001
  site_code: HTC
  subnet: 10.236.21.0.1/24
  vlan_id: 367
  vrf_name: vrf-htc_app_centric
- epg: epg-000089_001
  site_code: HTC
  subnet: 10.236.22.0.1/24
  vlan_id: 368
  vrf_name: vrf-htc_app_centric
- epg: epg-000090_001
  site_code: LVG
  subnet: 10.237.8.0.1/24
  vlan_id: 207
  vrf_name: vrf-lvg_app_centric
- epg: epg-000091_001
  site_code: LVG
  subnet: 10.237.9.0.1/24
  vlan_id: 208
  vrf_name: vrf-lvg_app_centric
- epg: epg-000090_001
  site_code: LVG
  subnet: 10.237.8.0.1/24
  vlan_id: 207
  vrf_name: vrf-lvg_app_centric
- epg: epg-000091_001
  site_code: LVG
  subnet: 10.237.9.0.1/24
  vlan_id: 208
  vrf_name: vrf-lvg_app_centric
